### ISSUE TITLE
Arte API changed, artep7 viewer doesn't work

### ISSUE THREAD

**Issue by tobika** [tobika/artep7viewer#2]
Modify the arteviewer to acces the new arte API under:
http://www.arte.tv/guide/api/api/program/fr/scheduled/17-04-25

**Comment by uahim** [comment]
actually it does work fine here, v2.6 in latest FF on Win7 x64 does at least

**Comment by tobika** [comment]
the url works yes, it's the new API endpoint, I have to change the artep7viewer to get the data from there :)
You are talking about what version 2.6? Ah I see, you are talking about the arte downloader? this is not the same project here ;) But even this is interesting, there is a issue with the downloader saying it doesn't work anymore:
https://github.com/GuGuss/ARTE-7-Downloader/issues/55

**Comment by tobika** [comment]
fixed
